spring.application.name=nexevent
nexevent.api-prefix =/api/v1
#POSTGRESQL
spring.datasource.url=jdbc:postgresql://ep-shiny-hat-aopsmpdz-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_UVf5xBonKu1t&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_UVf5xBonKu1t
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#JWT
ducthien.jwt.base64-secret=IX/V77D2EjGt7zLCCGZ8FIxtnRUOUGUNIYHp4zj4XaBKv3mQAgHtPa0RfjmoAg4JvdI2q7+MfQXLJrwNTcmiHg==
ducthien.jwt.access-token-validity-in-seconds=90000
ducthien.jwt.refresh-token-validity-in-seconds=90000