CREATE TABLE users (
                       id varchar(255) not null,
                       email varchar(100) not null unique,
                       password varchar(255) not null,
                       full_name varchar(100) not null,
                       phone varchar(11) not null,
                       role varchar(20) not null check ((role in ('USER','ADMIN','CHECKER'))),
                       is_active boolean not null,
                       created_at timestamp(6),
                       updated_at timestamp(6),
                       primary key (id)
);

CREATE TABLE events (
                        id bigint generated by default as identity,
                        title varchar(255) not null,
                        description TEXT,
                        cover varchar(255),
                        location varchar(255),
                        date timestamp(6),
                        start_time timestamp(6),
                        end_time timestamp(6),
                        active boolean,
                        created_at timestamp(6),
                        user_id varchar(255) not null,
                        primary key (id)
);

CREATE TABLE ticket_types (
                              id bigint generated by default as identity,
                              title varchar(255) not null,
                              price numeric(38,2) not null,
                              total_quantity integer not null,
                              sold_quantity integer,
                              status varchar(50) not null,
                              start_time timestamp(6),
                              end_time timestamp(6),
                              event_id bigint not null,
                              primary key (id)
);

CREATE TABLE orders (
                        id bigint generated by default as identity,
                        order_code varchar(30) not null unique,
                        total_amount numeric(38,2) not null,
                        status varchar(255) not null,
                        created_at timestamp(6),
                        user_id varchar(255) not null,
                        primary key (id)
);

CREATE TABLE order_items (
                             id bigint generated by default as identity,
                             quantity integer not null,
                             unit_price numeric(38,2) not null,
                             subtotal numeric(38,2) not null,
                             order_id bigint not null,
                             ticket_type_id bigint not null,
                             primary key (id)
);

CREATE TABLE tickets (
                         id varchar(255) not null,
                         status varchar(255) not null,
                         issued_at timestamp(6),
                         order_item_id bigint not null,
                         primary key (id)
);

CREATE TABLE checkins (
                          id bigint generated by default as identity,
                          gate varchar(255),
                          checkin_time timestamp(6),
                          staff_id varchar(255) not null,
                          ticket_id varchar(255) not null,
                          primary key (id)
);

-- ==========================================
-- 3. KHỞI TẠO KHÓA NGOẠI (FOREIGN KEYS)
-- ==========================================
ALTER TABLE IF EXISTS events
    ADD CONSTRAINT FKat8p3s7yjcp57lny4udqvqncq
    FOREIGN KEY (user_id) REFERENCES users;

ALTER TABLE IF EXISTS ticket_types
    ADD CONSTRAINT FKl83j9knh8jrssp3skaeubrrk
    FOREIGN KEY (event_id) REFERENCES events;

ALTER TABLE IF EXISTS orders
    ADD CONSTRAINT FK32ql8ubntj5uh44ph9659tiih
    FOREIGN KEY (user_id) REFERENCES users;

ALTER TABLE IF EXISTS order_items
    ADD CONSTRAINT FKbioxgbv59vetrxe0ejfubep1w
    FOREIGN KEY (order_id) REFERENCES orders;

ALTER TABLE IF EXISTS order_items
    ADD CONSTRAINT FKpcp79oqd3cihkrcb4j0bojtor
    FOREIGN KEY (ticket_type_id) REFERENCES ticket_types;

ALTER TABLE IF EXISTS tickets
    ADD CONSTRAINT FK1avmygv76x52clnkdj625qr7h
    FOREIGN KEY (order_item_id) REFERENCES order_items;

ALTER TABLE IF EXISTS checkins
    ADD CONSTRAINT FKapraqms7yxyaxmllc7c83na8f
    FOREIGN KEY (staff_id) REFERENCES users;

ALTER TABLE IF EXISTS checkins
    ADD CONSTRAINT FKfe12bbbyaw904r0yvsv4xfqst
    FOREIGN KEY (ticket_id) REFERENCES tickets;